#!/bin/sh

# 引入配置文件
. .git/hooks/config.sh

# 确保目录存在
if [ ! -d "$directory" ]; then
  echo "Directory $directory does not exist. Creating..."
  mkdir -p "$directory"
fi

# 使用当前时间戳生成处理后响应文件名
timestamp=$(date +%Y%m%d%H%M%S)
processedFilename="$directory/codeReviewResult_$timestamp.md"
originalFilename="codeReviewLog/originalFilename_$timestamp.json"

# 获取本次代码变更的内容并转义控制字符
changes=$(git diff --cached)
#echo "提交内容："
#echo "$changes"

# 转义换行符和引号
escapedChanges=$(echo "$changes" | tr '\n' ' ' | sed 's/\\n$//' | sed 's/\\$//')
escapedChanges=$(echo "$escapedChanges" | sed 's/"/\\"/g; s/\n/\\n/g')
#echo "转义后内容：$escapedChanges"

# 根据选择的模型调用不同的评审脚本
if [ "$selected_model" = "openai" ]; then
  . .git/hooks/glm_openai.sh "$escapedChanges" "$processedFilename" "$originalFilename"
elif [ "$selected_model" = "zhipu" ]; then
  . .git/hooks/glm_zhipu.sh "$escapedChanges" "$processedFilename" "$originalFilename"
else
  echo "未知模型，请检查配置文件中模型选择是否正确。"
fi