#!/bin/sh

# 引入配置文件
. .git/hooks/config.sh

# 确保目录存在
if [ ! -d "$directory" ]; then
  echo "Directory $directory does not exist. Creating..."
  mkdir -p "$directory"
fi

# 使用当前时间戳生成处理后响应文件名
timestamp=$(date +%Y%m%d%H%M%S)
processedFilename="$directory/codeReviewResult_$timestamp.md"
originalFilename="$directory/originalFilename_$timestamp.json"

# 获取本次代码变更的内容
changes=$(git diff --cached)

# 将变更内容保存到临时文件，避免命令行参数传递可能引起的问题
temp_changes_file=$(mktemp)
echo "$changes" > "$temp_changes_file"

# 根据选择的模型调用不同的评审脚本
if [ "$selected_model" = "openai" ]; then
  . .git/hooks/glm_openai.sh "$temp_changes_file" "$processedFilename" "$originalFilename"
elif [ "$selected_model" = "zhipu" ]; then
  . .git/hooks/glm_zhipu.sh "$temp_changes_file" "$processedFilename" "$originalFilename"
else
  echo "未知模型，请检查配置文件中模型选择是否正确。"
fi

# 清理临时文件
rm -f "$temp_changes_file"
