#!/bin/sh

# 启用调试输出
# set -x

# 引入配置文件
. "$(git rev-parse --show-toplevel)/.git/hooks/config.sh"

# 确保目录存在
if [ ! -d "$directory" ]; then
  echo "Directory $directory does not exist. Creating..."
  mkdir -p "$directory"
fi

# 使用当前时间戳生成处理后响应文件名
timestamp=$(date +%Y%m%d%H%M%S)
processedFilename="$directory/codeReviewResult_$timestamp.md"
originalFilename="$directory/originalFilename_$timestamp.json"

# 获取本次代码变更的内容
changes=$(git diff --cached)

# 检查是否有变更内容
if [ -z "$changes" ]; then
  echo "没有检测到代码变更，跳过评审"
  exit 0
fi

# 直接传递变更内容，不使用临时文件
if [ "$selected_model" = "openai" ]; then
  . "$(git rev-parse --show-toplevel)/.git/hooks/glm_openai.sh" "$changes" "$processedFilename" "$originalFilename"
elif [ "$selected_model" = "zhipu" ]; then
  . "$(git rev-parse --show-toplevel)/.git/hooks/glm_zhipu.sh" "$changes" "$processedFilename" "$originalFilename"
else
  echo "未知模型，请检查配置文件中模型选择是否正确。"
fi
